# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: 'Validate Code Owners'

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
    paths:
      - '.github/workflows/codeowners.yml'
      - '**/CODEOWNERS'
  pull_request_target:
    paths:
      - '.github/workflows/codeowners.yml'
      - '**/CODEOWNERS'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  codeowners:
    name: Shared Workflow
    uses: sassy-bulldog/.github/.github/workflows/codeowners.yml@v0.2.1 # x-release-please-version
    secrets: inherit
